# Development database
silq2-postgresql:
  container_name: silq2-postgresql
  image: postgres:9.5-alpine
  volumes:
    - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    - ./sql/qualis_evento.sql:/docker-entrypoint-initdb.d/2.sql
    - ./sql/qualis_periodico.sql:/docker-entrypoint-initdb.d/3.sql
  environment:
    - POSTGRES_DB=silq2
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"

# Test database
silq2-postgresql-tests:
  container_name: silq2-postgresql-tests
  image: postgres:9.5-alpine
  volumes:
    - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    - ./sql/qualis_evento.sql:/docker-entrypoint-initdb.d/2.sql
    - ./sql/qualis_periodico.sql:/docker-entrypoint-initdb.d/3.sql
  environment:
    - POSTGRES_DB=silq2
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
  ports:
    - "5430:5432"
